### ISSUE TITLE
Dataset rabbitmq_queues not found

### ISSUE THREAD

**Issue by madhur** [NYTimes/collectd-rabbitmq#45]
I keep getting this error

> TypeError: Dataset rabbitmq_queues not found
> Sep 23 00:09:25 app02 collectd[24906]: read-function of plugin `python.collectd_rabbitmq.collectd_plugin' failed. Will suspend it for 320.000 seconds.
> Sep 23 00:14:45 app02 collectd[24906]: Unhandled python exception in read callback: TypeError: Dataset rabbitmq_queues not found
> Sep 23 00:14:45 app02 collectd[24906]: Traceback (most recent call last):
> Sep 23 00:14:45 app02 collectd[24906]:   File "/usr/lib/python2.6/site-packages/collectd_rabbitmq/collectd_plugin.py", line 93, in read#012    PLUGIN.read()
> Sep 23 00:14:45 app02 collectd[24906]:   File "/usr/lib/python2.6/site-packages/collectd_rabbitmq/collectd_plugin.py", line 126, in read#012    self.dispatch_overview()
> Sep 23 00:14:45 app02 collectd[24906]:   File "/usr/lib/python2.6/site-packages/collectd_rabbitmq/collectd_plugin.py", line 217, in dispatch_overview#012    subtree_name, type_na

**Comment by jimbydamonk** [comment]
Does your collectd config include the custom datatypes ?
Example here: https://github.com/NYTimes/collectd-rabbitmq/blob/master/config/types.db.custom

Also, I have never testing with python 2.6 so there might be some issues there.

**Comment by madhur** [comment]
custom types was the issue.

**Comment by emraanali11** [comment]
Have update the types.db file, however still facing the issue. Sharing the error message along with collectd config. please help to fix.

Error Log:
[2017-12-13 11:28:30] Failed to dispatch rabbitmq_default.queues.xxx.get_details.avg. Exception Dataset get_details not found
[2017-12-13 11:28:30] Failed to dispatch rabbitmq_default.queues.xxx.get_details.avg_rate. Exception Dataset get_details not found
[2017-12-13 11:28:30] Failed to dispatch rabbitmq_default.queues.xxx.get_details.rate. Exception Dataset get_details not found
[2017-12-13 11:28:30] Failed to dispatch rabbitmq_default.queues.xxx.get_details.sample. Exception Dataset get_details not found
[2017-12-13 11:28:30] Failed to dispatch rabbitmq_default.queues.xxx.redeliver_details.avg. Exception Dataset redeliver_details not found
[2017-12-13 11:28:30] Failed to dispatch rabbitmq_default.queues.xxx.redeliver_details.avg_rate. Exception Dataset redeliver_details not found
[2017-12-13 11:28:30] Failed to dispatch rabbitmq_default.queues.xxx.redeliver_details.rate. Exception Dataset redeliver_details not found
[2017-12-13 11:28:30] Failed to dispatch rabbitmq_default.queues.xxx.redeliver_details.sample. Exception Dataset redeliver_details not found
[2017-12-13 11:28:30] Failed to dispatch rabbitmq_default.queues.xxx.consumers.None. Exception Dataset consumers not found
[2017-12-13 11:28:30] Failed to dispatch rabbitmq_default.queues.xxx.messages.None. Exception Dataset messages not found
[2017-12-13 11:28:30] Failed to dispatch rabbitmq_default.queues.xxx.messages_ready.None. Exception Dataset messages_ready not found

Collectd config:
TypesDB "/usr/share/collectd/types.db.custom"
LoadPlugin python
<Plugin python>
  LogTraces true
  Interactive false
  Import "collectd_rabbitmq.collectd_plugin"
  <Module "collectd_rabbitmq.collectd_plugin">

    Username "guest"
    Password "guest"
    Realm "RabbitMQ Management"
    Host "localhost"
    Port "15672"
  </Module>
</Plugin>
