### ISSUE TITLE
HTTP Error: HTTP Error 401: Unauthorized for new RabbitMQ 

### ISSUE THREAD

**Issue by Aidaho12** [NYTimes/collectd-rabbitmq#70]
Hi!

I have collectd-rabbitmq 1.20.0 and RabbitMQ 3.7.7. And all it togever gives empty metrics and errors:

```
liver.None. Exception Dataset redeliver not found
Nov  6 09:11:10 kz-graphite01 collectd: [2018-11-06 09:11:10] Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.return.None. Exception Dataset return not found
Nov  6 09:11:10 kz-graphite01 collectd: [2018-11-06 09:11:10] Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.consumers.None. Exception Dataset consumers not found
Nov  6 09:11:10 kz-graphite01 collectd: [2018-11-06 09:11:10] Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.consumer_utilisation.None. Exception Dataset consumer_utilisation not found
Nov  6 09:11:10 kz-graphite01 collectd: [2018-11-06 09:11:10] Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.messages.None. Exception Dataset messages not found
Nov  6 09:11:10 kz-graphite01 collectd: [2018-11-06 09:11:10] Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.messages_ready.None. Exception Dataset messages_ready not found
Nov  6 09:11:10 kz-graphite01 collectd: [2018-11-06 09:11:10] Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.messages_unacknowledged.None. Exception Dataset messages_unacknowledged not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RECHFULL_MTVAL50MT.consumer_utilisation.None. Exception Dataset consumer_utilisation not found
Nov  6 09:11:10 kz-graphite01 collectd: [2018-11-06 09:11:10] Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.ack.None. Exception Dataset ack not found
Nov  6 09:11:10 kz-graphite01 collectd: [2018-11-06 09:11:10] Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.publish.None. Exception Dataset publish not found
Nov  6 09:11:10 kz-graphite01 collectd: [2018-11-06 09:11:10] Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.publish_details.avg. Exception Dataset publish_details not found
Nov  6 09:11:10 kz-graphite01 collectd: [2018-11-06 09:11:10] Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.publish_details.avg_rate. Exception Dataset publish_details not found
Nov  6 09:11:10 kz-graphite01 collectd: [2018-11-06 09:11:10] Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.publish_details.rate. Exception Dataset publish_details not found
Nov  6 09:11:10 kz-graphite01 collectd: [2018-11-06 09:11:10] Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.publish_details.sample. Exception Dataset publish_details not found
Nov  6 09:11:10 kz-graphite01 collectd: [2018-11-06 09:11:10] Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.publish_in.None. Exception Dataset publish_in not found
Nov  6 09:11:10 kz-graphite01 collectd: [2018-11-06 09:11:10] Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.publish_out.None. Exception Dataset publish_out not found
Nov  6 09:11:10 kz-graphite01 collectd: [2018-11-06 09:11:10] Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.confirm.None. Exception Dataset confirm not found
Nov  6 09:11:10 kz-graphite01 collectd: [2018-11-06 09:11:10] Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.deliver.None. Exception Dataset deliver not found
Nov  6 09:11:10 kz-graphite01 collectd: [2018-11-06 09:11:10] Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.deliver_noack.None. Exception Dataset deliver_noack not found
Nov  6 09:11:10 kz-graphite01 collectd: [2018-11-06 09:11:10] Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.get.None. Exception Dataset get not found
Nov  6 09:11:10 kz-graphite01 collectd: [2018-11-06 09:11:10] Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.get_noack.None. Exception Dataset get_noack not found
Nov  6 09:11:10 kz-graphite01 collectd: [2018-11-06 09:11:10] Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.deliver_get.None. Exception Dataset deliver_get not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RECHFULL_MTVAL50MT.messages.None. Exception Dataset messages not found
Nov  6 09:11:10 kz-graphite01 collectd: [2018-11-06 09:11:10] Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.redeliver.None. Exception Dataset redeliver not found
Nov  6 09:11:10 kz-graphite01 collectd: [2018-11-06 09:11:10] Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.return.None. Exception Dataset return not found
Nov  6 09:11:10 kz-graphite01 collectd: [2018-11-06 09:11:10] Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.consumers.None. Exception Dataset consumers not found
Nov  6 09:11:10 kz-graphite01 collectd: [2018-11-06 09:11:10] Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.consumer_utilisation.None. Exception Dataset consumer_utilisation not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RECHFULL_MTVAL50MT.messages_ready.None. Exception Dataset messages_ready not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RECHFULL_MTVAL50MT.messages_unacknowledged.None. Exception Dataset messages_unacknowledged not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLSM.ack.None. Exception Dataset ack not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLSM.publish.None. Exception Dataset publish not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLSM.publish_details.avg. Exception Dataset publish_details not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLSM.publish_details.avg_rate. Exception Dataset publish_details not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLSM.publish_details.rate. Exception Dataset publish_details not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLSM.publish_details.sample. Exception Dataset publish_details not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLSM.publish_in.None. Exception Dataset publish_in not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLSM.publish_out.None. Exception Dataset publish_out not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLSM.confirm.None. Exception Dataset confirm not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLSM.deliver.None. Exception Dataset deliver not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLSM.deliver_noack.None. Exception Dataset deliver_noack not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLSM.get.None. Exception Dataset get not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLSM.get_noack.None. Exception Dataset get_noack not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLSM.deliver_get.None. Exception Dataset deliver_get not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLSM.redeliver.None. Exception Dataset redeliver not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLSM.return.None. Exception Dataset return not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLSM.consumers.None. Exception Dataset consumers not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLSM.consumer_utilisation.None. Exception Dataset consumer_utilisation not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLSM.messages.None. Exception Dataset messages not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLSM.messages_ready.None. Exception Dataset messages_ready not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLSM.messages_unacknowledged.None. Exception Dataset messages_unacknowledged not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_INFORMDAY.ack.None. Exception Dataset ack not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_INFORMDAY.publish.None. Exception Dataset publish not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_INFORMDAY.publish_details.avg. Exception Dataset publish_details not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_INFORMDAY.publish_details.avg_rate. Exception Dataset publish_details not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_INFORMDAY.publish_details.rate. Exception Dataset publish_details not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_INFORMDAY.publish_details.sample. Exception Dataset publish_details not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_INFORMDAY.publish_in.None. Exception Dataset publish_in not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_INFORMDAY.publish_out.None. Exception Dataset publish_out not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_INFORMDAY.confirm.None. Exception Dataset confirm not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_INFORMDAY.deliver.None. Exception Dataset deliver not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_INFORMDAY.deliver_noack.None. Exception Dataset deliver_noack not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_INFORMDAY.get.None. Exception Dataset get not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_INFORMDAY.get_noack.None. Exception Dataset get_noack not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_INFORMDAY.deliver_get.None. Exception Dataset deliver_get not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_INFORMDAY.redeliver.None. Exception Dataset redeliver not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_INFORMDAY.return.None. Exception Dataset return not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_INFORMDAY.consumers.None. Exception Dataset consumers not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_INFORMDAY.consumer_utilisation.None. Exception Dataset consumer_utilisation not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_INFORMDAY.messages.None. Exception Dataset messages not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_INFORMDAY.messages_ready.None. Exception Dataset messages_ready not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_INFORMDAY.messages_unacknowledged.None. Exception Dataset messages_unacknowledged not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.ack.None. Exception Dataset ack not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.publish.None. Exception Dataset publish not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.publish_details.avg. Exception Dataset publish_details not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.publish_details.avg_rate. Exception Dataset publish_details not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.publish_details.rate. Exception Dataset publish_details not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.publish_details.sample. Exception Dataset publish_details not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.publish_in.None. Exception Dataset publish_in not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.publish_out.None. Exception Dataset publish_out not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.confirm.None. Exception Dataset confirm not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.deliver.None. Exception Dataset deliver not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.deliver_noack.None. Exception Dataset deliver_noack not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.get.None. Exception Dataset get not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.get_noack.None. Exception Dataset get_noack not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.deliver_get.None. Exception Dataset deliver_get not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.redeliver.None. Exception Dataset redeliver not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.return.None. Exception Dataset return not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.consumers.None. Exception Dataset consumers not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.consumer_utilisation.None. Exception Dataset consumer_utilisation not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.messages.None. Exception Dataset messages not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.messages_ready.None. Exception Dataset messages_ready not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_MTVALLPSM.messages_unacknowledged.None. Exception Dataset messages_unacknowledged not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.ack.None. Exception Dataset ack not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.publish.None. Exception Dataset publish not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.publish_details.avg. Exception Dataset publish_details not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.publish_details.avg_rate. Exception Dataset publish_details not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.publish_details.rate. Exception Dataset publish_details not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.publish_details.sample. Exception Dataset publish_details not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.publish_in.None. Exception Dataset publish_in not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.publish_out.None. Exception Dataset publish_out not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.confirm.None. Exception Dataset confirm not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.deliver.None. Exception Dataset deliver not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.deliver_noack.None. Exception Dataset deliver_noack not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.get.None. Exception Dataset get not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.get_noack.None. Exception Dataset get_noack not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.deliver_get.None. Exception Dataset deliver_get not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.redeliver.None. Exception Dataset redeliver not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.return.None. Exception Dataset return not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.consumers.None. Exception Dataset consumers not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.consumer_utilisation.None. Exception Dataset consumer_utilisation not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.messages.None. Exception Dataset messages not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.messages_ready.None. Exception Dataset messages_ready not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RENOCH_EVA.messages_unacknowledged.None. Exception Dataset messages_unacknowledged not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RECHFULL_MTV_PST.ack.None. Exception Dataset ack not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RECHFULL_MTV_PST.publish.None. Exception Dataset publish not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RECHFULL_MTV_PST.publish_details.avg. Exception Dataset publish_details not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RECHFULL_MTV_PST.publish_details.avg_rate. Exception Dataset publish_details not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RECHFULL_MTV_PST.publish_details.rate. Exception Dataset publish_details not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RECHFULL_MTV_PST.publish_details.sample. Exception Dataset publish_details not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RECHFULL_MTV_PST.publish_in.None. Exception Dataset publish_in not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RECHFULL_MTV_PST.publish_out.None. Exception Dataset publish_out not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RECHFULL_MTV_PST.confirm.None. Exception Dataset confirm not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RECHFULL_MTV_PST.deliver.None. Exception Dataset deliver not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RECHFULL_MTV_PST.deliver_noack.None. Exception Dataset deliver_noack not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RECHFULL_MTV_PST.get.None. Exception Dataset get not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RECHFULL_MTV_PST.get_noack.None. Exception Dataset get_noack not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RECHFULL_MTV_PST.deliver_get.None. Exception Dataset deliver_get not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RECHFULL_MTV_PST.redeliver.None. Exception Dataset redeliver not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RECHFULL_MTV_PST.return.None. Exception Dataset return not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RECHFULL_MTV_PST.consumers.None. Exception Dataset consumers not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RECHFULL_MTV_PST.consumer_utilisation.None. Exception Dataset consumer_utilisation not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RECHFULL_MTV_PST.messages.None. Exception Dataset messages not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RECHFULL_MTV_PST.messages_ready.None. Exception Dataset messages_ready not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_RECHFULL_MTV_PST.messages_unacknowledged.None. Exception Dataset messages_unacknowledged not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_ACTIVATE.ack.None. Exception Dataset ack not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_ACTIVATE.ack_details.avg. Exception Dataset ack_details not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_ACTIVATE.ack_details.avg_rate. Exception Dataset ack_details not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_ACTIVATE.ack_details.rate. Exception Dataset ack_details not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Failed to dispatch rabbitmq_default.queues.itpss_ACTIVATE.ack_details.sample. Exception Dataset ack_details not found
Nov  6 09:11:10 kz-graphite01 collectd[8865]: HTTP Error: HTTP Error 401: Unauthorized
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Unhandled python exception in read callback: TypeError: 'NoneType' object is not iterable
Nov  6 09:11:10 kz-graphite01 collectd[8865]: Traceback (most recent call last):
Nov  6 09:11:10 kz-graphite01 collectd[8865]:  File "/usr/lib/python2.7/site-packages/collectd_rabbitmq-1.20.0-py2.7.egg/collectd_rabbitmq/collectd_plugin.py", line 94, in read#012    instance.read()
Nov  6 09:11:10 kz-graphite01 collectd[8865]:  File "/usr/lib/python2.7/site-packages/collectd_rabbitmq-1.20.0-py2.7.egg/collectd_rabbitmq/collectd_plugin.py", line 131, in read#012    self.dispatch_exchanges(vhost_name)
Nov  6 09:11:10 kz-graphite01 collectd[8865]:  File "/usr/lib/python2.7/site-packages/collectd_rabbitmq-1.20.0-py2.7.egg/collectd_rabbitmq/collectd_plugin.py", line 273, in dispatch_exchanges#012    stats = self.rabbit.get_exchange_stats(vhost_name=vhost_name)
Nov  6 09:11:10 kz-graphite01 collectd[8865]:  File "/usr/lib/python2.7/site-packages/collectd_rabbitmq-1.20.0-py2.7.egg/collectd_rabbitmq/rabbit.py", line 146, in get_exchange_stats#012    return self.get_stats('exchange', exchange_name, vhost_name)
Nov  6 09:11:10 kz-graphite01 collectd[8865]:  File "/usr/lib/python2.7/site-packages/collectd_rabbitmq-1.20.0-py2.7.egg/collectd_rabbitmq/rabbit.py", line 197, in get_stats#012    names = stat_name_func(vhost)
Nov  6 09:11:10 kz-graphite01 collectd[8865]:  File "/usr/lib/python2.7/site-packages/collectd_rabbitmq-1.20.0-py2.7.egg/collectd_rabbitmq/rabbit.py", line 137, in get_exchange_names#012    return self.get_names(all_exchanges)
Nov  6 09:11:10 kz-graphite01 collectd[8865]:  File "/usr/lib/python2.7/site-packages/collectd_rabbitmq-1.20.0-py2.7.egg/collectd_rabbitmq/rabbit.py", line 43, in get_names#012    for item in items:
Nov  6 09:11:10 kz-graphite01 collectd[8865]: TypeError: 'NoneType' object is not iterable
```

**Comment by ghost** [comment]
Set your `Realm` to `RabbitMQ Management`.

The readme says it defaults to that, but it doesn't. It defaults to `RabbitMQ`. 

At least, that fixed it for me. 🤷‍♂️

**Comment by ghost** [comment]
Regarding all of the `Failed to dispatch` messages, you missed running this line here:

`cp /usr/share/collectd/types.db{,.backup}; cat config/types.db.custom >> /usr/share/collectd/types.db` 

That and the realm should fix your problems :)
